name: Build

on: [push]

jobs:
  build-bam:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Checkout bam
      uses: actions/checkout@v2
      with:
        repository: matricks/bam
        ref: 4bffc62aa4bb184dfcd338d15d63903e561dcbed
        path: ./bam
    - name: Prepare Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -y
        sudo apt-get install libfreetype6-dev libsdl2-dev -y
        cd bam
        ./make_unix.sh
    - name: Build in debug mode
      run: ./bam/bam server_debug
    - name: Test debug
      run: ./teeworlds_srv_d shutdown

    - name: Build in release mode
      run: ./bam/bam server_release
    - name: Test release
      run: ./teeworlds_srv shutdown

    - name: Pack linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        tar cf tw-plus-linux.tar.xz teeworlds_srv
        mkdir artifacts
        mv tw-plus-linux.tar.xz artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: tw-plus-${{ matrix.os }}
        path: artifacts
